### ISSUE TITLE
MBKC

### ISSUE THREAD

**Issue by MiaH1nojosa123** [CodeChica/SparkleHub-lite#8]
As a sparkler, I want to add a sound when you send a sparkle, so that it feels more accomplishing to send it to someone. 

Project Break Down: made by k.c and bella
* [x] Research how to create a sound when clicking a button. 
* [x] Build a prototype of the sound clicking. 
* [x] Share a demo of the prototype and collect feedback from the group. 
* [x] Trigger the sound as the Sparkle is saved. 
* [x] Stop the sound after `2` seconds using a timer. 
* [x] Add automated tests for each of the browsers that we support. 
* [x] Work with Design to choose sounds that go with the theme.
* [x] Add acceptanced tests for the new sound. 

Team Member Include: 
- Mia Hinojosa (Project Manager/Designer) 
- Bella Hinojosa (Engineer)
- K.C. (Engineer) 
- Celinne Gautier (Project Manager/Designer)

**Comment by Mellow-Marsh** [comment]
<img width="1080" alt="Screenshot 2021-11-06 at 12 52 49" src="https://user-images.githubusercontent.com/90232044/140620808-f9299f33-2aea-423a-a313-879694912ca4.png">

**Comment by bellaiscool93** [comment]
/Users/christopherhinojosa/showcase/index.html
